define({
    streetLength: 3060.0 + 1338.0,
    stepLength: 100,
    streetWidth: 1099.5,
    landmarks: [
        {
            km: 0,
            name: 'Дворцовая пл.',
            type: 'square',
        },
        {
            km: 171,
            name: 'Адмиралтейская',
            type: 'metro',
            width: 20,
        },
        {
            km: 412,
            name: 'Мойка',
            type: 'river',
            width: 33,
        },
        {
            km: 556,
            name: 'Большая Конюшенская ул.',
            type: 'street',
            width: 22.7,
            position: 'top',
            doubled: true,
        },
        {
            km: 779,
            name: 'Казанский собор',
            type: 'building',
        },
        {
            km: 798,
            name: 'Канал Грибоедова',
            type: 'river',
            width: 18,
        },
        {
            km: 1030,
            name: 'Думская ул.',
            type: 'street',
            width: 27.2,
            position: 'bottom',
            doubled: true,
        },
        {
            km: 1030,
            name: 'Михайловская ул.',
            type: 'street',
            width: 12.2,
            position: 'top',
        },
        {
            km: 950,
            name: 'Невский проспект',
            type: 'metro',
        },
        {
            km: 1230,
            name: 'Гостиный двор',
            type: 'metro',
        },
        {
            km: 1300,
            name: 'Садовая ул.',
            type: 'street',
            width: 10.9,
            position: 'both',
        },
        {
            km: 1430,
            name: 'Екатериненский сквер',
            type: 'park',
        },
        {
            km: 1780,
            name: 'Фонтанка',
            type: 'river',
            width: 52,
        },
        {
            km: 2040,
            name: 'Владимерский пр-т',
            type: 'street',
            width: 12.7,
            position: 'bottom',
        },
        {
            km: 2040,
            name: 'Литейный пр-т',
            type: 'street',
            width: 12.7,
            position: 'top',
        },
        {
            km: 2470,
            name: 'Маяковская',
            type: 'metro',
        },
        {
            km: 2840,
            name: 'Площадь Восстания',
            type: 'metro',
            top: true,
        },
        {
            km: 2840,
            name: 'Пл. Восстания',
            type: 'square',
        },
        {
            km: 3060,
            name: 'Суворовский пр-т',
            type: 'street',
            width: 16.3,
            position: 'top',
        },
        {
            km: 3930,
            name: 'Исполкомская ул.',
            type: 'street',
            width: 12.2,
            position: 'top',
        },
        {
            km: 3060.0 + 1338.0,
            name: 'Александра Невского',
            type: 'metro',
        },
        {
            km: 3060.0 + 1338.0,
            name: 'Пл. Александра Невского',
            type: 'square',
        },
    ],
})